/**
 * This code was generated by Builder.io.
 */
import Image from "next/image";

const TestimonialCard = ({ name, major, imageSrc }) => {
  return (
    <div className="flex flex-col flex-wrap content-start px-5 py-7 bg-blue-300 rounded-3xl max-md:pr-5">
      <div className="flex gap-3.5 text-xl font-semibold leading-3">
        <Image
          src={imageSrc}
          alt={`${name}'s profile`}
          width={69}
          height={62}
          className="shrink-0 bg-white"
        />
        <div>
          {name} <span className="text-lg text-sky-900">{major}</span>
        </div>
      </div>
      <div className="mt-7 text-4xl font-extrabold leading-5">
        " <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> "
      </div>
    </div>
  );
};

const Testimonials = () => {
  const testimonials = [
    {
      name: "Rahul Rangaraaj",
      major: "Major",
      imageSrc: "http://b.io/placeholder-profile",
    },
    {
      name: "Jane Doe",
      major: "Major",
      imageSrc: "http://b.io/placeholder-profile",
    },
    {
      name: "John Smith",
      major: "Major",
      imageSrc: "http://b.io/placeholder-profile",
    },
    // Add more testimonials as needed
  ];

  return (
    <section className="mt-20 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-5xl font-extrabold text-slate-400 max-md:max-w-full max-md:text-4xl">
        What <span className="text-slate-400">Students</span> Are Saying
      </h2>
      <p className="mt-3.5 text-2xl font-medium leading-10 text-center text-cyan-700 max-md:max-w-full">
        Hear from thousands of successful applicants
      </p>
      <div className="flex overflow-x-auto gap-5 justify-between self-stretch px-5 mt-12 w-full text-sky-900 max-md:flex-wrap max-md:mt-10 max-md:max-w-full">
        {testimonials.map((testimonial, index) => (
          <TestimonialCard key={index} {...testimonial} />
        ))}
      </div>
    </section>
  );
};

export default Testimonials;
