/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TestimonialCard = ({ name, major, testimonial }) => {
  return (
    <div className="flex flex-col p-6 bg-customBlue rounded-2xl w-72">
      <div className="flex items-center gap-3 mb-4">
        <div className="avatar bg-white" />
        <div>
          <div className="font-semibold">{name}</div>
          <div className="text-sm text-sky-900">{major}</div>
        </div>
      </div>
      <p className="text-lg font-medium leading-relaxed">
        <span className="text-xl text-db mr-1">&ldquo;</span>
        {testimonial}
        <span className="text-xl text-db ml-1">&rdquo;</span>
      </p>
    </div>
  );
};

export default TestimonialCard;
